/**
 * scripts/seed.js
 *
 * One-time seed script. Run ONCE before or after first deployment:
 *
 *   node scripts/seed.js
 *
 * What it does:
 *   1. Reads every asset from /public/ (images, SVGs, PDFs)
 *   2. Uploads each to Vercel Blob and records the returned URL
 *   3. Loads defaultContent.ts values (via a pre-built JSON snapshot)
 *   4. Replaces every /public/-relative path in the content with its Blob URL
 *   5. Writes the fully-resolved content to Upstash Redis under 'bunny-cms-content'
 *
 * Prerequisites:
 *   - UPSTASH_REDIS_REST_URL and UPSTASH_REDIS_REST_TOKEN in your environment
 *     (copy from the Upstash dashboard or Vercel project settings)
 *   - BLOB_READ_WRITE_TOKEN in your environment
 *     (copy from Vercel Blob → project settings → tokens)
 *   - Node.js 18+ (uses fetch natively)
 *
 * Run with env vars:
 *   UPSTASH_REDIS_REST_URL=https://... \
 *   UPSTASH_REDIS_REST_TOKEN=... \
 *   BLOB_READ_WRITE_TOKEN=vercel_blob_rw_... \
 *   node scripts/seed.js
 */

import { Redis } from '@upstash/redis';
import { put } from '@vercel/blob';
import { readFileSync, readdirSync, statSync } from 'fs';
import { join, extname, basename } from 'path';
import { fileURLToPath } from 'url';

const __dirname = fileURLToPath(new URL('.', import.meta.url));
const PUBLIC_DIR = join(__dirname, '..', 'public');
const CONTENT_KEY = 'bunny-cms-content';

// ── Load defaultContent from the compiled JSON snapshot ────────
// We import the snapshot rather than the TS source to avoid needing
// a TypeScript compiler at seed time.
// After running `npm run build` once, the content is baked into the
// site bundle. For the seed we use a hand-maintained JSON that mirrors
// defaultContent.ts exactly. It is generated by `npm run export-defaults`.
//
// If the snapshot doesn't exist yet, read defaultContent.ts as text
// and extract the exported object using a simple regex. This is fragile
// but sufficient for a one-time seed.

async function loadDefaultContent() {
  // Try the pre-built snapshot first
  const snapshotPath = join(__dirname, 'default-content-snapshot.json');
  try {
    const raw = readFileSync(snapshotPath, 'utf8');
    return JSON.parse(raw);
  } catch {
    // Fallback: import the TS file via dynamic import (requires tsx/ts-node)
    console.warn('No snapshot found. Attempting dynamic import of defaultContent.ts…');
    try {
      const mod = await import('../src/content/defaultContent.ts');
      return mod.default ?? mod;
    } catch (e) {
      throw new Error(
        'Could not load defaultContent. Run: npm run export-defaults\n' + e.message
      );
    }
  }
}

// ── Enumerate uploadable public assets ────────────────────────
const UPLOAD_EXTS = new Set(['.png', '.jpg', '.jpeg', '.svg', '.webp', '.pdf', '.ico']);

function collectPublicAssets(dir, prefix = '') {
  const entries = readdirSync(dir);
  const files = [];
  for (const entry of entries) {
    const full = join(dir, entry);
    const stat = statSync(full);
    if (stat.isDirectory()) {
      files.push(...collectPublicAssets(full, `${prefix}/${entry}`));
    } else if (UPLOAD_EXTS.has(extname(entry).toLowerCase())) {
      files.push({ localPath: full, publicPath: `${prefix}/${entry}` });
    }
  }
  return files;
}

// ── Upload one file to Vercel Blob ────────────────────────────
async function uploadAsset({ localPath, publicPath }) {
  const data = readFileSync(localPath);
  const filename = basename(localPath);

  // Determine content type
  const ext = extname(localPath).toLowerCase();
  const mimeMap = {
    '.png': 'image/png', '.jpg': 'image/jpeg', '.jpeg': 'image/jpeg',
    '.svg': 'image/svg+xml', '.webp': 'image/webp',
    '.pdf': 'application/pdf', '.ico': 'image/x-icon',
  };
  const contentType = mimeMap[ext] ?? 'application/octet-stream';

  const blob = await put(`cms-assets${publicPath}`, data, {
    access: 'public',
    contentType,
    addRandomSuffix: false, // keep deterministic URLs
  });

  return { publicPath, blobUrl: blob.url };
}

// ── Replace /public/-relative paths in content JSON ──────────
function replaceAssetPaths(obj, urlMap) {
  if (typeof obj === 'string') {
    // Match /path.ext patterns that exist in our map
    if (urlMap[obj]) return urlMap[obj];
    return obj;
  }
  if (Array.isArray(obj)) return obj.map(item => replaceAssetPaths(item, urlMap));
  if (obj && typeof obj === 'object') {
    const out = {};
    for (const [k, v] of Object.entries(obj)) {
      out[k] = replaceAssetPaths(v, urlMap);
    }
    return out;
  }
  return obj;
}

// ── Main ──────────────────────────────────────────────────────
async function main() {
  console.log('=== Bunny Industries CMS Seed Script ===\n');

  // Validate env vars
  const required = ['UPSTASH_REDIS_REST_URL', 'UPSTASH_REDIS_REST_TOKEN', 'BLOB_READ_WRITE_TOKEN'];
  const missing = required.filter(k => !process.env[k]);
  if (missing.length > 0) {
    console.error('Missing required env vars:', missing.join(', '));
    console.error('\nUsage:');
    console.error('  UPSTASH_REDIS_REST_URL=... UPSTASH_REDIS_REST_TOKEN=... BLOB_READ_WRITE_TOKEN=... node scripts/seed.js');
    process.exit(1);
  }

  const redis = new Redis({
    url: process.env.UPSTASH_REDIS_REST_URL,
    token: process.env.UPSTASH_REDIS_REST_TOKEN,
  });

  // ── Step 1: Collect assets
  console.log('Step 1: Collecting /public/ assets…');
  const assets = collectPublicAssets(PUBLIC_DIR);
  console.log(`  Found ${assets.length} uploadable files.\n`);

  // ── Step 2: Upload all to Blob
  console.log('Step 2: Uploading to Vercel Blob…');
  const urlMap = {};
  let uploaded = 0;
  let failed = 0;

  for (const asset of assets) {
    try {
      process.stdout.write(`  [${++uploaded}/${assets.length}] ${asset.publicPath} … `);
      const { blobUrl } = await uploadAsset(asset);
      urlMap[asset.publicPath] = blobUrl;
      console.log(`✓ ${blobUrl}`);
    } catch (err) {
      failed++;
      console.error(`✗ FAILED: ${err.message}`);
    }
  }

  console.log(`\n  Uploaded: ${uploaded - failed}/${assets.length} files.`);
  if (failed > 0) console.warn(`  ⚠ ${failed} files failed — check BLOB_READ_WRITE_TOKEN and retry.`);

  // Save URL map for reference
  const mapJson = JSON.stringify(urlMap, null, 2);
  const { writeFileSync } = await import('fs');
  writeFileSync(join(__dirname, 'blob-url-map.json'), mapJson, 'utf8');
  console.log('\n  URL map saved to scripts/blob-url-map.json\n');

  // ── Step 3: Load default content
  console.log('Step 3: Loading default content…');
  const defaultContent = await loadDefaultContent();
  console.log('  ✓ Default content loaded.\n');

  // ── Step 4: Replace paths with Blob URLs
  console.log('Step 4: Replacing /public/ paths with Blob URLs…');
  const seededContent = replaceAssetPaths(defaultContent, urlMap);
  let replacements = 0;
  const originalStr = JSON.stringify(defaultContent);
  const seededStr = JSON.stringify(seededContent);
  // Count how many URLs were replaced
  Object.values(urlMap).forEach(url => {
    if (seededStr.includes(url)) replacements++;
  });
  console.log(`  ✓ ${replacements} asset path(s) replaced with Blob URLs.\n`);

  // ── Step 5: Write to Redis
  console.log('Step 5: Writing seeded content to Upstash Redis…');
  await redis.set(CONTENT_KEY, JSON.stringify(seededContent));
  console.log('  ✓ Content written to Redis.\n');

  // Verify
  const readback = await redis.get(CONTENT_KEY);
  const verified = readback && typeof readback === 'object'
    ? Object.keys(readback).length > 0
    : false;
  console.log(`  ✓ Verification: ${verified ? 'PASS — content readable from Redis.' : 'FAIL — nothing read back!'}\n`);

  console.log('=== Seed complete ===');
  console.log('Next steps:');
  console.log('  1. Deploy imsweb: vercel --prod');
  console.log('  2. Deploy imscontroller: vercel --prod (from same repo, different project)');
  console.log('  3. Open https://imscontroller.vercel.app/controller → password in VITE_CONTROLLER_PASSWORD');
  console.log('  4. Verify site renders at https://imsweb.vercel.app');
}

main().catch(err => {
  console.error('\n[FATAL]', err);
  process.exit(1);
});
